name: Continuous Integration - iburguer-onboarding

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  OnBoarding-Tests:
    runs-on: ubuntu-latest
    environment: 
      name: Iburguer

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install Amazon.Lambda.Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
    
    - name: Run Tests
      run: dotnet test ../../iBurguer.Onboarding/test/iBurguer.Onboarding.Tests

      